### ISSUE TITLE
库的问题

### ISSUE THREAD

**Issue by q32784307** [xuuhan/HXPhotoBrowser#2]
您好，请问您的这个SDWebImage是哪个版本的？最新的5.0版本，SDWebImageManager类中- (void)diskImageExistsForURL:(nullable NSURL *)url completion:(nullable SDWebImageCheckCacheCompletionBlock)completionBlock；这个方法废弃了..

**Comment by q32784307** [comment]
- (void)sd_setFadeImageWithURL:(nullable NSURL *)url
          placeholderImage:(nullable UIImage *)placeholder
                   options:(SDWebImageOptions)options
                  progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                 completed:(nullable SDExternalCompletionBlock)completedBlock;
这个方法中的SDWebImageDownloaderProgressBlock，最新的库里也是出问题了

**Comment by xuuhan** [comment]
之前依赖了SDWebImage4，现在更新成了依赖SDWebImage5
